<Select.Option value="us-east-2">US East (Ohio)</Select.Option>
<Select.Option value="us-east-1">US East (N. Virginia)</Select.Option>
<Select.Option value="us-west-1">US West (N. California)</Select.Option>
<Select.Option value="us-west-2">US West (Oregon)</Select.Option>
<Select.Option value="af-south-1">Africa (Cape Town)</Select.Option>
<Select.Option value="ap-east-1">Asia Pacific (Hong Kong)</Select.Option>
<Select.Option value="ap-south-1">Asia Pacific (Mumbai)</Select.Option>
<Select.Option value="ap-northeast-3">Asia Pacific (Osaka-Local)</Select.Option>
<Select.Option value="ap-northeast-2">Asia Pacific (Seoul)</Select.Option>
<Select.Option value="ap-southeast-1">Asia Pacific (Singapore)</Select.Option>
<Select.Option value="ap-southeast-2">Asia Pacific (Sydney)</Select.Option>
<Select.Option value="ap-northeast-1">Asia Pacific (Tokyo)</Select.Option>
<Select.Option value="ca-central-1">Canada (Central)</Select.Option>
<Select.Option value="cn-north-1">China (Beijing)</Select.Option>
<Select.Option value="cn-northwest-1">China (Ningxia)</Select.Option>
<Select.Option value="eu-central-1">Europe (Frankfurt)</Select.Option>
<Select.Option value="eu-west-1">Europe (Ireland)</Select.Option>
<Select.Option value="eu-west-2">Europe (London)</Select.Option>
<Select.Option value="eu-south-1">Europe (Milan)</Select.Option>
<Select.Option value="eu-west-3">Europe (Paris)</Select.Option>
<Select.Option value="eu-north-1">Europe (Stockholm)</Select.Option>
<Select.Option value="me-south-1">Middle East (Bahrain)</Select.Option>
<Select.Option value="sa-east-1">South America (São Paulo)</Select.Option>
<Select.Option value="us-gov-east-1">AWS GovCloud (US-East)</Select.Option>
<Select.Option value="us-gov-west-1">AWS GovCloud (US)</Select.Option>
